### ISSUE TITLE
希望添加2个汉字,非常感谢！

### ISSUE THREAD

**Issue by Dukethomas** [TakWolf/fusion-pixel-font#11]
使用中发现缺少2个汉字
简体“骷髅”的"髅"
简体和繁体,"猛犸"的"犸"

希望开发者能够添加,非常感谢！

**Comment by TakWolf** [comment]
今天晚上解决

**Comment by TakWolf** [comment]
`骷髅猛犸髏獁`

以上字符可用，下载 https://github.com/TakWolf/fusion-pixel-font/releases/tag/2023.02.13

这版开始拆分比例和等宽模式，模式和【方舟像素字体】相同，可以参考：https://github.com/TakWolf/ark-pixel-font#%E5%AE%BD%E5%BA%A6%E6%A8%A1%E5%BC%8F

新版等宽模式相当于旧版本。

有问题随时反馈
