### ISSUE TITLE
Is it possible to provide italic font face that only modifies those English alphabets? (keep Chinese characters intact)

### ISSUE THREAD

**Issue by nyngwang** [TakWolf/fusion-pixel-font#14]
As title.

**Comment by TakWolf** [comment]
What's type of italic?

Vector italic:

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/6064962/224875680-0f9ad256-3660-48c6-9aeb-a302b96eb3a2.png">

Pixel original style:

![image](https://user-images.githubusercontent.com/6064962/224876214-a95d17a3-7940-4901-850b-33b41b353bbe.png)

**Comment by TakWolf** [comment]
This project will not provide italic build as official. Our main goal is for pixel game develop as main text font. Exact pixel, sans-serif, goshikku is the target style. 

But, I can create a other branch (project) to solve your problem, add some special scripts. This is not particularly complicated. (As I have free time)


Vector italic can be easily realize, for example css:

```css
.italic {
       font-style: italic;
}
```

as code may here https://github.com/TakWolf/fusion-pixel-font/blob/master/utils/glyph_util.py#L48  add some params like gradient.

BUt this is not real pixel italic, but seems like as pixel feel.

The real pixel style is the second case, need to be remade and designed.

**Comment by TakWolf** [comment]
Approximate effect for the original italic pixel style:

https://static.takwolf.com/demo/fusion-pixel-font-issues-14/

Use the fallback font Xilla:  https://www.dafont.com/xilla.font
