### ISSUE TITLE
字距显示不正常

### ISSUE THREAD

**Issue by CXido** [TakWolf/fusion-pixel-font#18]
我下载的是OTF版本的字体，发现在AI和PS中调用字体，字会叠在一起

![image](https://github.com/TakWolf/fusion-pixel-font/assets/55381745/4ae415b2-0bdd-4ef5-ae98-569ecf88a333)
![image](https://github.com/TakWolf/fusion-pixel-font/assets/55381745/848ff29b-ddf6-401d-be7c-5dcb4771e3d2)

**Comment by TakWolf** [comment]
啊？其他布局引擎都是正常的

是需要特殊参数兼容吗？

我回去找一个 PS 试一下

**Comment by TakWolf** [comment]
Windows 8.1  photoshop CS6

![image](https://github.com/TakWolf/fusion-pixel-font/assets/6064962/bc088a44-1b48-4777-bc5b-844db2573d8a)
![image](https://github.com/TakWolf/fusion-pixel-font/assets/6064962/546225fb-66ec-4980-8b59-6ef72de5d9da)

拉丁字母字距确实不正常。选择无后所有字都重合了。

我也不知道为啥。。。。。

**Comment by TakWolf** [comment]
macOS Krita  正常

<img width="903" alt="image" src="https://github.com/TakWolf/fusion-pixel-font/assets/6064962/13435f82-fa10-41d8-9fb0-4b73e2d2349e">

**Comment by TakWolf** [comment]
> 从 ttf 子集化生成的 woff2 不会重叠，这个 woff2 和 release 里的 woff2 会有什么区别吗？

目前 Releases 里面的 `woff2` 是基于 `otf` 的压缩版本，本质上等同于 `otf`

所以实际上是 `otf` 有问题，`ttf` 无问题。

但是我现在也不知道为什么会有这个问题，很奇怪。

我不确定到底是不是和 Windows 平台有关系。按道理布局需要的必要参数都有。但是 OpenType 确实有平台相关的参数（参考：https://glyphsapp.com/zh/learn/vertical-metrics）。

**Comment by TransparentLC** [comment]
用 2023.04.26 测试了上面六种情况，没有重叠问题了。

**Comment by TakWolf** [comment]
> 用 2023.04.26 测试了上面六种情况，没有重叠问题了。

间距正常吗？指半角占用 6px，全角12px。可视字空隙 1px。

正确的渲染应该是这样的：

![image](https://github.com/TakWolf/fusion-pixel-font/assets/6064962/1c30d386-b2dc-4aad-afdd-be4cb5507991)

如果正常那就是这个问题了。

补一个源代码，他没有解释过这个 width 到底是什么？有可能 T2CharString 布局时这个 `width` 和 `advance_width` 都有作用

```
class T2CharStringPen(BasePen):
    """Pen to draw Type 2 CharStrings.

    The 'roundTolerance' argument controls the rounding of point coordinates.
    It is defined as the maximum absolute difference between the original
    float and the rounded integer value.
    The default tolerance of 0.5 means that all floats are rounded to integer;
    a value of 0 disables rounding; values in between will only round floats
    which are close to their integral part within the tolerated range.
    """

    def __init__(self, width, glyphSet, roundTolerance=0.5, CFF2=False):
        super(T2CharStringPen, self).__init__(glyphSet)
        self.round = roundFunc(roundTolerance)
        self._CFF2 = CFF2
        self._width = width
        self._commands = []
        self._p0 = (0, 0)
```

**Comment by TransparentLC** [comment]
是这个样子，每个字之间大概一个像素点的空隙。

我对字体格式相关的这些底层原理不太熟……

**Comment by TakWolf** [comment]
正式版已发布

https://github.com/TakWolf/fusion-pixel-font/releases/tag/2023.07.19
