### ISSUE TITLE
有些字仍未改成简中写法

### ISSUE THREAD

**Issue by Yave-Yu** [TakWolf/fusion-pixel-font#19]
12px 版我目前发现的：滑、解、残、零，在 GB2312 范围内可能还有更多。

**Comment by TakWolf** [comment]
这是因为这个项目是一个临时性的补字方案。

它的基础是 https://github.com/TakWolf/ark-pixel-font 的汉字。但是因为方舟目前还没有完成（到今天为止 12px 大概还有不到 1800 GB2312 汉字未完成，统一汉字区块还有大概 8000 个左右汉字未完成），没法用于生产环境。

为了能让它有一定可用性，才有了「缝合」这个项目，相当于用方舟汉字作为基础，用 [俐方體11號／Cubic 11](https://github.com/ACh-K/Cubic-11) 和 [Galmuri](https://github.com/quiple/galmuri) 来补充缺失的汉字。

方舟的字形是经过设计的，理论上是正确的简体字形。但是 立方体11 和 Galmuri 基本上是繁体写法。所以目前才是这样的。
