### ISSUE TITLE
建议添加 TTC 格式

### ISSUE THREAD

**Issue by Scratchbin** [TakWolf/fusion-pixel-font#22]
如题

**Comment by TakWolf** [comment]
构建系统 https://github.com/TakWolf/pixel-font-builder 暂时不支持 TTC 和 OTC 构建（需要一种 API 设计）。

另外，我不确定是否应该支持集合字体格式，或者异体字选择器特性

**Comment by TakWolf** [comment]
已添加 TTC 和 OTC 格式，请查看快照版本：https://github.com/TakWolf/fusion-pixel-font/releases/tag/snapshot

正式版稍后推出

**Comment by TakWolf** [comment]
目前导出格式 Windows 存在问题。

上游：https://github.com/TakWolf/pixel-font-builder/issues/2

**Comment by TakWolf** [comment]
https://github.com/TakWolf/fusion-pixel-font/releases/tag/2023.08.09

已正式添加 OTC 和 TTC 格式支持
