### ISSUE TITLE
8 像素字體繁體中文的標點符號格式沒有置中

### ISSUE THREAD

**Issue by nekolyst** [TakWolf/fusion-pixel-font#23]
10 和 12 像素字體繁體中文符號正常置中，但是 8 像素的繁體中文符號卻是靠左下角。
看了下第三方字體：精品點陣體7×7，繁體中文是置中的。
再麻煩修正了，感謝！

**Comment by TakWolf** [comment]
https://github.com/TakWolf/fusion-pixel-font/releases/tag/2023.08.09

已重新修正相关标点符号
