### ISSUE TITLE
【询问】语言特定字形版本的差异

### ISSUE THREAD

**Issue by JustusPan** [TakWolf/fusion-pixel-font#24]
你好，
这里有一些关于特定字形版本的疑问：
请问不同的语言特定字形版本是否均包含了所有语言字符的完整支持？
比如zh_hans与ja是否均支持中日韩英所有字符，区别只是优先选择的汉字字形不同？
也即是说，如果要支持多语言的话，任取一种语言特定字形版本就足够吗？

**Comment by TakWolf** [comment]
> 请问不同的语言特定字形版本是否均包含了所有语言字符的完整支持？
> 比如zh_hans与ja是否均支持中日韩英所有字符，区别只是优先选择的汉字字形不同？
对的。

例如，“画”这个字，中日写法不同
<img width="428" alt="image" src="https://github.com/TakWolf/fusion-pixel-font/assets/6064962/2ecc0980-f873-427e-b615-98ef4f791fb8">
但是，他们的 Unicode 码位都是 U+753B。（这根 Unicode 的一些历史遗留问题有关，解释起来比较复杂，总之现在存在很多这种情况的汉字）

如果只使用单一码点的话，就没有办法同时支持两种语言的显示。所以就做成两个版本，其中zh_hans 的版本中心就是田字， ja 的版本中心就是由字。

最佳做法是，你给中文翻译文本使用 zh_hans.ttf，给日语翻译使用 ja.ttf 版本。但是这样就需要同时包含两份字体，体积会变大，程序上也要实现一个动态字体载入。

你也可以只使用其中一份字体。这样另外一种语言的使用者看起来可能就有违和感。一般来说，大陆这边天生自带繁体识别技能，对这个情况其实不敏感(例如 B 站很多视频字幕使用的是日语字体，字形并不是国标，很多人不提醒也不太会注意)。但是港台日那边违和感是情况我不太确定。

具体怎么选择需要你自己来权衡。

另外附近里面也有个 ttc （otc）版本，是多个字体打包一起的集合字体格式，共享了大量字形数据，所以比单独引用5份单独的字体体积要小很多。如果你的游戏引擎支持这个格式也可以用，但是貌似大部分都不支持该格式。

**Comment by TakWolf** [comment]
我看到你貌似在使用 Godot。 
Godot 4.1.2 完全支持  otc 和 ttc 格式。

<img width="619" alt="image" src="https://github.com/TakWolf/fusion-pixel-font/assets/6064962/058b01ac-0a77-43e2-995c-8b4e4325fb94">

face_index 属性就是表示具体使用的集合字体中的那一个。
0~4分别对应   拉丁、简中、繁中、日语、韩语

修改语言选项的时候动态修改这个值就可以改变字体，这是目前最佳方案！

**Comment by JustusPan** [comment]
感谢解读。我原本打算使用woff2因为它的体积最小，但是如果考虑到字形版本最后如果带了复数个woff2，似乎不如otc的方案来的简洁。
当前我的理解如下：
1）fusion pixel的所有特定字形版本均包含一样的unicode字符支持。不考虑某些地区阅读违和感的话，可以仅选一种woff2或者其他非collection类型的格式（ttf,otf,woff),即可支持所有语言。在引擎工具中也无需对多语言部分的字体特殊处理。
2）如果非collection类型的的格式希望在多语言系统中显示正确的字形，那么需要引入5份woff2。其中，各语言拥有相同字形的所有字符会产生5倍冗余。
3）collection类型的格式包含了各种字型，拥有相同字形的各语言不产生冗余。

选择字体的依据：
当各种格式都被支持时：
1）只有两个最优解，otc或者woff2
2）如果想要优雅一些，单一otc文件即可（12px mono：5135kb）
3）需要极限小体积的话，比较woff2所有字形版本累积体积与otc的体积，较小的更优, 在这个例子中应该选woff2（woff2五种字形文件累计大小2771kb < 5135kb)

**Comment by TakWolf** [comment]
> 感谢解读。我原本打算使用woff2因为它的体积最小，但是如果考虑到字形版本最后如果带了复数个woff2，似乎不如otc的方案来的简洁。 当前我的理解如下： 1）fusion pixel的所有特定字形版本均包含一样的unicode字符支持。不考虑某些地区阅读违和感的话，可以仅选一种woff2或者其他非collection类型的格式（ttf,otf,woff),即可支持所有语言。在引擎工具中也无需对多语言部分的字体特殊处理。 2）如果非collection类型的的格式希望在多语言系统中显示正确的字形，那么需要引入5份woff2。其中，各语言拥有相同字形的所有字符会产生5倍冗余。 3）collection类型的格式包含了各种字型，拥有相同字形的各语言不产生冗余。
> 
> 选择字体的依据： 当各种格式都被支持时： 1）只有两个最优解，otc或者woff2 2）如果想要优雅一些，单一otc文件即可（12px mono：5135kb） 3）需要极限小体积的话，比较woff2所有字形版本累积体积与otc的体积，较小的更优, 在这个例子中应该选woff2（woff2五种字形文件累计大小2771kb < 5135kb)

理解完全正确。

补充几点：

1.  woff / woff2 实际上是 otf / ttf 的压缩版本，加载过程先要解压为 otf / ttf ，然后在按照 OpenType 规范解析结构。流程会多一个步骤，会额外消耗性能。web 上大体积造成的网络加载时间要更长，相比之下本地解压时间基本可以忽略不计，所以在此场景下 woff 格式更好。

2. Chrome / CSS 目前规范中不支持集合字体，所以 otc / ttc 没有对应的 woff 格式规范

3. 语言特定字形除了影响汉字外，也影响标点符号。比如：全角逗号和句号，大陆国标是位于左下角的，港台则居中显示；全角单双引号，只有中日韩是全角的，西文仍然是半角（因此有一个单独的拉丁分流版本来提供西文习惯标点）
