### ISSUE TITLE
Missing character: add 债啧帻渍碛箦绩责赜 to 10px

### ISSUE THREAD

**Issue by fooks-dot** [TakWolf/fusion-pixel-font#25]
Apologies for writing in English - I unfortunately don't speak Chinese :/ 

We noticed that this character was missing from the Fusion Pixel font: 啧

I was advised on your Discord to post here with the following characters: 债啧帻渍碛箦绩责赜

Thanks again for your amazing font, keep up the great work!

**Comment by TakWolf** [comment]
It's me. 😂

Try this version: https://github.com/TakWolf/fusion-pixel-font/releases/tag/snapshot

**Comment by fooks-dot** [comment]
Thanks a lot for being so reactive! We'll give it a try and I'll keep you posted :)

**Comment by fooks-dot** [comment]
Hey, thanks again for helping with this issue, it's now fixed!
