### ISSUE TITLE
Missing characters: add 埚 & 濑 to 10px

### ISSUE THREAD

**Issue by fooks-dot** [TakWolf/fusion-pixel-font#26]
Hello, me again! We're still in the process of implementing the font, so I haven't been able to verify your addition for my previous request for 啧 (https://github.com/TakWolf/fusion-pixel-font/issues/25). My apologies.

I do have another request for the following characters, which I don't think are present in the 10px font: 

埚

濑

Thanks in advance!

**Comment by TakWolf** [comment]
Add: 埚呙涡锅赖濑

<img width="140" alt="image" src="https://github.com/TakWolf/fusion-pixel-font/assets/6064962/74a9ae6d-d2a3-4469-8056-e08704aac4df">
