### ISSUE TITLE
希望可以添加nerd font系列字体, 

### ISSUE THREAD

**Issue by CG-man** [TakWolf/fusion-pixel-font#6]
主要是扔到代码编辑器用, 我的图标全变成方块了QAQ
<img width="593" alt="image" src="https://user-images.githubusercontent.com/12809498/170215990-55ceab2d-bbe5-4f99-909c-7109c23b7723.png">

**Comment by TakWolf** [comment]
https://github.com/ryanoasis/nerd-fonts

这个他不是像素字体啊

**Comment by TakWolf** [comment]
这个问题应该判定为不解决。

nerd font 并不是像素字体，不符合字源规则，并且目前的构建系统也无法兼容。

关于是否应该在私用区添加自定义字符，且应该补充那些，属于另外的问题，应该发起单独的线程来讨论。

有任何想法和问题，请重新打开这个线程，或补充新的留言。

**Comment by TakWolf** [comment]
@CG-man 简单来说，就是通过其他工具合并两个字体。

实际上并不需要这么麻烦，合并字体有更简单的工具，比如：https://github.com/nowar-fonts/Warcraft-Font-Merger

**Comment by TakWolf** [comment]
@nyngwang 

 This project will not directly support nerd as a font source, because this is not inconformity with the goal.
